Feature/rename project
green-code-initiative/creedengo-csharp-sonarqube pull request #9
Opened 2024-12-11 16:40 UTC by vincent314

Caution: merge after PR #8

2024-12-31 10:51 UTC, dedece35 requested changes

2024-12-31 10:51 UTC, dedece35 commented on README.md
> +| 1.1.0+         | 9.9.+ LTS to 10.5.1 | 1.1.0                           |
please add a new line with 2.0.0 version (it will be the next release with renaming work included)

2024-12-31 10:51 UTC, dedece35 commented on pom.xml
>    <version>1.5.2-SNAPSHOT</version>
please change version to 2.0.0-SNAPSHOT

2025-01-13 15:30 UTC, jay-79 requested changes

2025-01-13 15:37 UTC, jay-79 commented
Hi @vincent314, can you please merge #9 and #8 from your side in the same PR ?
That will be easier to merge whole changes at once and have all check passing smoothly.
Thx

2025-02-17 00:37 UTC, jay-79 commented
Complete with PR#11

2025-02-17 00:37 UTC, closed without merging